services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: squadride
      POSTGRES_USER: squadride_user
      POSTGRES_PASSWORD: squadride_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - squad-ride-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/squadride
      - SPRING_DATASOURCE_USERNAME=squadride_user
      - SPRING_DATASOURCE_PASSWORD=squadride_pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - db
    networks:
      - squad-ride-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://backend:8080/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - squad-ride-network
networks:
  squad-ride-network:
    driver: bridge
volumes:
  pgdata:
