name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2"  # or latest

      - name: Install dependencies
        run: cd mobile && cd squad_ride && flutter pub get

      - name: Run analyzer
        run: cd mobile && cd squad_ride && flutter analyze

      - name: Run tests
        run: cd mobile && cd squad_ride && flutter test

      - name: Notify Discord
        if: always()
        run: |
          STATUS=${{ job.status }}
          curl -H "Content-Type: application/json" \
            -X POST -d "{\"content\": \"GitHub Actions CI: $STATUS for [${{ github.repository }}@${{ github.ref_name }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}